title: RecSys 2022 Tweets Analysis
description: Analysis of the interaction between Twitter users during the ACM RecSys 2022 conference.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
