title: RecSys 2022 Tweets Analysis
description: Analysis of the interaction between Twitter users during the ACM RecSys 2022 conference.
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

